import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { ThemeProvider } from 'next-themes'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import { QueryProvider } from '@/providers/providers'
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin'
import { extractRouterConfig } from 'uploadthing/server'
import { fileRouter } from './api/uploadthing/core'

const geistSans = localFont({
   src: './fonts/GeistVF.woff',
   variable: '--font-geist-sans',
})
const geistMono = localFont({
   src: './fonts/GeistMonoVF.woff',
   variable: '--font-geist-mono',
})

export const metadata: Metadata = {
   title: {
      template: '%s | bugbook',
      default: 'bugbook',
   },
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang='en'>
         <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <NextSSRPlugin routerConfig={extractRouterConfig(fileRouter)} />
            <QueryProvider>
               <ThemeProvider
                  attribute='class'
                  defaultTheme='system'
                  enableSystem
                  disableTransitionOnChange
                  themes={['light', 'dark', 'system']}
               >
                  {children}
               </ThemeProvider>
            </QueryProvider>
            <Toaster />
         </body>
      </html>
   )
}
